kind: pipeline
type: docker
name: Docs deploy

trigger:
  branch:
    - master

volumes:
  - name: deploy
    host:
      path: /root/html/naomi.plus

steps:
  - name: Build & Deploy
    image: gplane/pnpm:9-node20
    environment:
      NODE_OPTIONS: --max_old_space_size=2048
    volumes:
      - name: deploy
        path: /drone/src/dist
    commands:
      - pnpm config set registry https://mirrors.tencent.com/npm/
      - pnpm config list
      - pnpm install --frozen-lockfile
      - sed -i 's/naomi233.github.io/www.naomi.plus/' docs/.vuepress/theme.ts
      - sed -i "s#MIT Licensed#<a href='https://beian.miit.gov.cn/' target='_blank'>粤ICP备19151060号-2</a>#" docs/.vuepress/theme.ts
      - pnpm run build
