name: Gitea Actions Build

on:
  push:
    paths-ignore:
      - .github/**
      - .commitlintrc.cjs
      - .drone.yml
      - .editorconfig
      - .gitignore
      - .markdownlint.json
      - .prettierignore
      - .prettierrc.cjs
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      volumes:
        - /root/html/naomi.plus:/tmp/dist
    steps:
      - name: Checkout
        uses: https://gitee.com/actions-mirror/checkout@v4
        with:
          fetch-depth: 0
        #   如果你文档需要 Git 子模块，取消注释下一行
        #   submodules: true

      - name: 安装 pnpm
        uses: https://gitee.com/mys1024/actions-setup-pnpm@v4
        with:
          version: 10

      - name: 设置 Node.js
        uses: https://gitee.com/actions-mirror/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          registry-url: https://mirrors.tencent.com/npm/

      - name: Install dependencies
        run: pnpm install

      - name: Build artifact
        id: build
        env:
          NODE_OPTIONS: --max_old_space_size=2048
        run: |-
          sed -i 's/naomi233.github.io/www.naomi.plus/' docs/.vuepress/theme.ts
          sed -i "s#MIT Licensed#<a href='https://beian.miit.gov.cn/' target='_blank'>粤ICP备19151060号-2</a>#" docs/.vuepress/theme.ts
          pnpm run build
          rm -rf /tmp/dist/*
          cp -r dist/* /tmp/dist

      # - name: Upload artifact
      #   uses: https://gitee.com/actions-mirror/upload-artifact@v3
      #   with:
      #     path: dist
