name: GitHub pages deploy

on:
  push:
    branches:
      - master
    paths-ignore:
      - .commitlintrc.cjs
      - .drone.yml
      - .editorconfig
      - .gitignore
      - .markdownlint.json
      - .prettierignore
      - .prettierrc.cjs
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: build
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # 如果你文档需要 Git 子模块，取消注释下一行
          # submodules: true

      - name: 安装 pnpm
        uses: pnpm/action-setup@v3
        with:
          run_install: true
          version: 8

      - name: 设置 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Build artifact
        id: build
        env:
          NODE_OPTIONS: --max_old_space_size=8192
        run: |-
          sed -i 's/www.naomi.plus/naomi233.github.io/' docs/.vuepress/theme.ts
          pnpm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy-gh-pages:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
